platform :ios, '10.0'
workspace 'BlueWallet'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 
target 'BlueWallet' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

end


target 'BlueWalletWatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #  use_frameworks!
  # Pods for BlueWalletWatch
  platform :watchos, '5.0'
end

target 'BlueWalletWatch Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #  use_frameworks!
  platform :watchos, '5.0'
  pod 'EFQRCode', '5.1.0'
  # Pods for BlueWalletWatch Extension
end
