default_platform(:ios)

app_store_connect_api_key(
  key_id: ENV["FASTLANE_APP_STORE_CONNECT_API_KEY_ID"],
  issuer_id: ENV["FASTLANE_APP_STORE_CONNECT_API_ISSUER_ID"],
  key_filepath: ENV["FASTLANE_APP_STORE_CONNECT_API_KEY_FILEPATH"],
  in_house: false
)

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy do
  ensure_git_status_clean

  increment_build_number(xcodeproj: "ios/BlueWallet.xcodeproj") # Update path as needed

  sh "npm install"

  # Install pods
  cocoapods(repo_update: true)

  match(
    type: "appstore",
    app_identifier: [
      "io.bluewallet.bluewallet",                # Main App
      "io.bluewallet.bluewallet.watch",          # Watch App
      "io.bluewallet.bluewallet.watch.extension",# Watch Extension
      "io.bluewallet.bluewallet.Stickers",       # Stickers Extension
      "io.bluewallet.bluewallet.MarketWidget",         # Widget Extension
    ],
    team_id: ENV["ITC_TEAM_ID"], # Your Apple Developer Account Team ID
    team_name: ENV["ITC_TEAM_NAME"] # Optional: Your Apple Developer Account Team Name
  )

    # Synchronize certificates and provisioning profiles for each scheme
    synchronize_profiles(schemes: {
      "BlueWallet" => "io.bluewallet.bluewallet",
      "BlueWalletWatch" => "io.bluewallet.bluewallet.watch",
      "BlueWalletWatch Extension" => "io.bluewallet.bluewallet.watch.extension",
      "Stickers" => "io.bluewallet.bluewallet.Stickers",
      "WidgetsExtension" => "io.bluewallet.bluewallet.MarketWidget"
    })

    # Build the main app
    build_app(
      scheme: "BlueWallet",
      workspace: "ios/BlueWallet.xcworkspace",
      export_method: "app-store",
      export_team_id: ENV["ITC_TEAM_ID"],
    )

    # Upload to TestFlight
    upload_to_testflight(skip_waiting_for_build_processing: false)

    # Clean up build artifacts
    clean_build_artifacts
  end

  private_lane :synchronize_profiles do |options|
    options[:schemes].each do |scheme, identifier|
      match(type: "appstore", app_identifier: identifier, team_id: ENV["ITC_TEAM_ID"]) # Specify the team ID here
    end
  end
end