#!/bin/bash
#
# sync-android-locales.sh
#
# Syncs Android locale support with the language list in loc/languages.ts:
#   1. Generates res/xml/locale_config.xml (Android 13+ per-app language picker)
#   2. Creates res/values-XX/ folders with a minimal strings.xml for each locale
#   3. Adds android:localeConfig to AndroidManifest.xml if missing
#
# Usage: Run manually or as a Gradle task:
#   ./scripts/sync-android-locales.sh [--dry-run]
#
# Options:
#   --dry-run   Show what would change without writing any files
#

set -euo pipefail

DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
  esac
done

# --- Helpers ------------------------------------------------------------------

log()  { echo "[sync-android-locales] $*"; }
warn() { echo "[sync-android-locales] WARNING: $*" >&2; }
die()  { echo "[sync-android-locales] ERROR: $*" >&2; exit 1; }

# Temp files tracked for cleanup
TMPFILES=()
cleanup() {
  for f in "${TMPFILES[@]:-}"; do
    [ -n "$f" ] && [ -f "$f" ] && rm -f "$f"
  done
  return 0
}
trap cleanup EXIT

# Create a temp file in the same directory as $1 (atomic mv on same filesystem)
make_tmp() {
  local dir
  dir="$(dirname "$1")"
  local tmp
  tmp="$(mktemp "$dir/.sync-android-locales.XXXXXX")" || die "Cannot create temp file in $dir"
  TMPFILES+=("$tmp")
  echo "$tmp"
}

# Write $2 to file $1 atomically (temp + mv). Skips if content matches.
# Returns 0 if file was updated, 1 if unchanged.
atomic_write() {
  local target="$1" content="$2"
  if [ -f "$target" ] && [ "$(cat "$target")" = "$content" ]; then
    return 1
  fi
  if $DRY_RUN; then
    return 0
  fi
  local tmp
  tmp="$(make_tmp "$target")"
  printf '%s\n' "$content" > "$tmp"
  mv -f "$tmp" "$target"
}

# --- Pre-flight checks --------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LANGUAGES_TS="$REPO_ROOT/loc/languages.ts"
RES_DIR="$REPO_ROOT/android/app/src/main/res"
MANIFEST="$REPO_ROOT/android/app/src/main/AndroidManifest.xml"

command -v python3 >/dev/null 2>&1 || die "python3 is required but not found in PATH"

[ -f "$LANGUAGES_TS" ] || die "Source file not found: $LANGUAGES_TS"
[ -r "$LANGUAGES_TS" ] || die "Source file not readable: $LANGUAGES_TS"

if ! $DRY_RUN; then
  [ -d "$RES_DIR" ] || die "Android res directory not found: $RES_DIR"
  [ -w "$RES_DIR" ] || die "Android res directory not writable: $RES_DIR"
fi

# --- Extract locales from languages.ts ----------------------------------------

LOCALES=()
while IFS= read -r locale; do
  [ -n "$locale" ] && LOCALES+=("$locale")
done < <(python3 -c "
import re, sys
with open(sys.argv[1], 'r') as f:
    content = f.read()
for m in re.finditer(r\"appleLocale:\s*'([^']+)'\", content):
    print(m.group(1))
" "$LANGUAGES_TS" 2>&1) || die "Failed to parse locales from $LANGUAGES_TS"

[ "${#LOCALES[@]}" -gt 0 ] || die "Parsed 0 locales from $LANGUAGES_TS — file may be malformed"

# Sort and deduplicate
IFS=$'\n' SORTED_LOCALES=($(printf '%s\n' "${LOCALES[@]}" | sort -u)); unset IFS

log "Found ${#SORTED_LOCALES[@]} locale(s) in languages.ts"

# --- 1. Generate locale_config.xml --------------------------------------------

XML_DIR="$RES_DIR/xml"
LOCALE_CONFIG="$XML_DIR/locale_config.xml"

CONFIG_CONTENT='<?xml version="1.0" encoding="utf-8"?>
<locale-config xmlns:android="http://schemas.android.com/apk/res/android">
    <locale android:name="en" />'
for locale in "${SORTED_LOCALES[@]}"; do
  [ "$locale" = "en" ] && continue
  CONFIG_CONTENT+=$'\n'"    <locale android:name=\"$locale\" />"
done
CONFIG_CONTENT+=$'\n''</locale-config>'

if $DRY_RUN; then
  if [ -f "$LOCALE_CONFIG" ] && [ "$(cat "$LOCALE_CONFIG")" = "$CONFIG_CONTENT" ]; then
    log "locale_config.xml already up-to-date"
  else
    log "[dry-run] Would update locale_config.xml (${#SORTED_LOCALES[@]} locales)"
  fi
else
  mkdir -p "$XML_DIR" || die "Cannot create directory: $XML_DIR"
  if atomic_write "$LOCALE_CONFIG" "$CONFIG_CONTENT"; then
    log "Generated locale_config.xml with ${#SORTED_LOCALES[@]} locale(s)"
  else
    log "locale_config.xml already up-to-date"
  fi
fi

# --- 2. Create values-XX/ resource folders ------------------------------------

# Android uses values-b+XX+YY for BCP-47 tags with subtags
# e.g., zh-Hans -> values-b+zh+Hans, es-419 -> values-b+es+419, pt-BR -> values-b+pt+BR
android_res_folder() {
  local locale="$1"
  if [[ "$locale" == *-* ]]; then
    local converted
    converted=$(echo "$locale" | sed 's/-/+/g')
    echo "values-b+${converted}"
  else
    echo "values-${locale}"
  fi
}

STRINGS_CONTENT='<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- This file registers the locale for Android per-app language support.
         Auto-generated by scripts/sync-android-locales.sh -->
</resources>'

created_count=0
for locale in "${SORTED_LOCALES[@]}"; do
  [ "$locale" = "en" ] && continue
  folder_name=$(android_res_folder "$locale")
  folder_path="$RES_DIR/$folder_name"
  strings_file="$folder_path/strings.xml"

  if $DRY_RUN; then
    if [ ! -d "$folder_path" ]; then
      log "[dry-run] Would create $folder_name/"
      created_count=$((created_count + 1))
    fi
    continue
  fi

  if [ ! -d "$folder_path" ]; then
    mkdir -p "$folder_path" || die "Cannot create directory: $folder_path"
    created_count=$((created_count + 1))
  fi
  # Write strings.xml atomically (only if missing or changed)
  if [ ! -f "$strings_file" ]; then
    atomic_write "$strings_file" "$STRINGS_CONTENT" || true
  fi
done

if [ "$created_count" -gt 0 ]; then
  if $DRY_RUN; then
    log "[dry-run] Would create $created_count new values-XX/ folder(s)"
  else
    log "Created $created_count new values-XX/ folder(s)"
  fi
else
  log "All values-XX/ folders already exist"
fi

# --- 3. Add localeConfig to AndroidManifest.xml if missing --------------------

if [ ! -f "$MANIFEST" ]; then
  warn "AndroidManifest.xml not found at $MANIFEST — skipping"
elif ! $DRY_RUN && [ ! -w "$MANIFEST" ]; then
  die "AndroidManifest.xml is not writable: $MANIFEST"
elif grep -q 'android:localeConfig' "$MANIFEST"; then
  log "AndroidManifest.xml already has android:localeConfig"
else
  MANIFEST_RESULT="$(python3 -c "
import re, sys

manifest_path = sys.argv[1]
dry_run = sys.argv[2] == 'true'

with open(manifest_path, 'r', encoding='utf-8') as f:
    content = f.read()

pattern = r'(android:configChanges=\"[^\"]*\")'
replacement = r'\1\n        android:localeConfig=\"@xml/locale_config\"'
new_content, count = re.subn(pattern, replacement, content, count=1)

if count == 0:
    print('NO-MATCH', end='')
    sys.exit(0)

if dry_run:
    print('WOULD-ADD', end='')
    sys.exit(0)

import os, tempfile, shutil
target_dir = os.path.dirname(manifest_path)
fd, tmp_path = tempfile.mkstemp(dir=target_dir, prefix='.manifest-sync-', suffix='.tmp')
try:
    with os.fdopen(fd, 'w', encoding='utf-8') as f:
        f.write(new_content)
    shutil.move(tmp_path, manifest_path)
except BaseException:
    os.unlink(tmp_path)
    raise

print('ADDED', end='')
" "$MANIFEST" "$DRY_RUN" 2>&1)" || die "Failed to update AndroidManifest.xml"

  case "$MANIFEST_RESULT" in
    NO-MATCH)  warn "Could not find insertion point in AndroidManifest.xml (no android:configChanges attribute)" ;;
    WOULD-ADD) log "[dry-run] Would add android:localeConfig to AndroidManifest.xml" ;;
    ADDED)     log "Added android:localeConfig to AndroidManifest.xml" ;;
    *)         warn "Unexpected result from manifest update: $MANIFEST_RESULT" ;;
  esac
fi

log "Android locale sync complete."
