import loc from '../loc';

export type HeaderMenuShortcut = { input: string; modifiers: ('command' | 'shift' | 'alternate')[] };

// Avoid standard text-editing shortcuts and shortcuts that broadcast or sign funds.
export const headerMenuShortcuts: Record<string, HeaderMenuShortcut> = {
  share: { input: 's', modifiers: ['command', 'shift'] },
  copyToClipboard: { input: 'c', modifiers: ['command', 'alternate'] },
  scan_qr: { input: 'i', modifiers: ['command', 'alternate'] },
  file_save: { input: '\r', modifiers: ['command'] },
  edit_reset: { input: 'r', modifiers: ['command', 'alternate'] },
  edit_wallet_name: { input: 'r', modifiers: ['command', 'alternate'] },
  view_addresses: { input: 'a', modifiers: ['command', 'alternate'] },
  view_contacts: { input: 'n', modifiers: ['command', 'alternate'] },
  view_xpub: { input: 'x', modifiers: ['command', 'alternate'] },
  file_sign_verify: { input: 'v', modifiers: ['command', 'alternate'] },
  file_export_setup: { input: 'e', modifiers: ['command', 'shift', 'alternate'] },
  edit_cosigners: { input: 'k', modifiers: ['command', 'alternate'] },
  file_custom_amount: { input: 'm', modifiers: ['command', 'alternate'] },
  file_receive_options: { input: 'o', modifiers: ['command', 'alternate'] },
  edit_address_label: { input: 'l', modifiers: ['command', 'alternate'] },
  view_verify_transaction: { input: 'v', modifiers: ['command', 'alternate'] },
  view_address_qr: { input: 'q', modifiers: ['command', 'alternate'] },
  AddRecipient: { input: 'n', modifiers: ['command', 'shift'] },
  insert_contact: { input: 'n', modifiers: ['command', 'alternate'] },
  import_transaction: { input: 'i', modifiers: ['command', 'shift'] },
  import_transaction_multisig: { input: 'i', modifiers: ['command', 'shift'] },
  import_transaction_qr: { input: 'i', modifiers: ['command', 'alternate'] },
  import_file: { input: 'i', modifiers: ['command', 'shift'] },
  choose_photo: { input: 'p', modifiers: ['command', 'shift'] },
  ExportTransaction: { input: 'e', modifiers: ['command', 'shift'] },
  TransactionDetailsButton: { input: 'd', modifiers: ['command', 'alternate'] },
  viewInBitcoin: { input: '1', modifiers: ['command', 'alternate'] },
  viewInSats: { input: '2', modifiers: ['command', 'alternate'] },
  viewInFiat: { input: '3', modifiers: ['command', 'alternate'] },
  hideBalance: { input: 'b', modifiers: ['command', 'alternate'] },
  copyBalance: { input: 'c', modifiers: ['command', 'alternate'] },
  open_block_explorer: { input: 'e', modifiers: ['command', 'alternate'] },
  ExportWallet: { input: 'e', modifiers: ['command', 'shift'] },
  changeBalanceUnit: { input: 'u', modifiers: ['command', 'shift'] },
  coin_control: { input: 'c', modifiers: ['command', 'alternate'] },
  ModalDoneButton: { input: '\r', modifiers: ['command'] },
  NavigationCloseButton: { input: 'w', modifiers: ['command'] },
};

export const headerMenuShortcutHelp = () => [
  { title: loc.receive.details_share, key: 'Shift+S', where: loc._.menu_file },
  { title: loc.transactions.details_copy, key: 'Option+C', where: loc._.menu_edit },
  { title: loc.wallets.import_scan_qr, key: 'Option+I', where: loc._.menu_file },
  { title: loc.receive.details_save, key: 'Return', where: loc._.menu_file },
  { title: loc.receive.reset, key: 'Option+R', where: loc._.menu_edit },
  { title: loc.wallets.details_show_addresses, key: 'Option+A', where: loc.wallets.details_title },
  { title: loc.wallets.details_show_xpub, key: 'Option+X', where: loc.wallets.details_title },
  { title: loc.bip47.contacts, key: 'Option+N', where: loc.wallets.details_title },
  { title: loc.receive.details_setAmount, key: 'Option+M', where: loc.receive.header },
  { title: loc.receive.option_label, key: 'Option+L', where: loc.receive.header },
  { title: loc.send.create_verify, key: 'Option+V', where: loc._.menu_transaction },
  { title: loc.send.details_add_rec_add, key: 'Shift+N', where: loc._.menu_recipients },
  { title: loc.send.details_insert_contact, key: 'Option+N', where: loc._.menu_recipients },
  { title: loc.send.details_adv_import, key: 'Shift+I', where: loc._.menu_transaction },
  { title: loc.send.details_adv_import_qr, key: 'Option+I', where: loc._.menu_transaction },
  { title: loc.wallets.import_file, key: 'Shift+I', where: loc.send.details_scan },
  { title: loc.wallets.list_long_choose, key: 'Shift+P', where: loc.send.details_scan },
  { title: loc.multisig.share, key: 'Shift+E', where: loc._.menu_transaction },
  { title: loc.send.create_details, key: 'Option+D', where: loc._.menu_transaction },
  { title: loc.units.BTC, key: 'Option+1', where: loc.wallets.balance_unit },
  { title: loc.units.sats, key: 'Option+2', where: loc.wallets.balance_unit },
  { title: loc.wallets.local_currency, key: 'Option+3', where: loc.wallets.balance_unit },
  { title: loc.transactions.details_balance_hide, key: 'Option+B', where: loc.transactions.list_title },
  { title: loc.wallets.copy_balance, key: 'Option+C', where: loc.transactions.list_title },
  { title: loc.wallets.open_block_explorer, key: 'Option+E', where: loc.transactions.list_title },
  { title: loc.wallets.details_export_backup, key: 'Shift+E', where: loc.wallets.details_title },
  { title: loc.wallets.change_balance_unit, key: 'Shift+U', where: loc.transactions.list_title },
  { title: loc.cc.header, key: 'Option+C', where: loc._.menu_transaction },
  { title: loc.send.input_done, key: 'Return', where: loc.multisig.vault_advanced_customize },
  { title: loc._.close, key: 'W / Esc', where: loc._.menu_close_scope },
];
