export const AvailableLanguages: Readonly<TLanguage[]> = Object.freeze([
  { label: 'English', value: 'en', appleLocale: 'en' },
  { label: 'Afrikaans (AFR)', value: 'zar_afr', appleLocale: 'af' },
  { label: 'العربية (AR)', value: 'ar', isRTL: true, appleLocale: 'ar' },
  { label: 'Български (BG)', value: 'bg_bg', appleLocale: 'bg' },
  { label: 'Беларускі (BE)', value: 'be', appleLocale: 'be' },
  { label: 'Català (CA)', value: 'ca', appleLocale: 'ca' },
  { label: 'Chinese (TW)', value: 'zh_tw', appleLocale: 'zh-Hant' },
  { label: 'Chinese (ZH)', value: 'zh_cn', appleLocale: 'zh-Hans' },
  { label: 'Croatian (HR)', value: 'hr_hr', appleLocale: 'hr' },
  { label: 'Cymraeg (CY)', value: 'cy', appleLocale: 'cy' },
  { label: 'Česky (CZ)', value: 'cs_cz', appleLocale: 'cs' },
  { label: 'Danish (DK)', value: 'da_dk', appleLocale: 'da' },
  { label: 'Deutsch (DE)', value: 'de_de', appleLocale: 'de' },
  { label: 'Español (Spain) (es_ES)', value: 'es', appleLocale: 'es' },
  { label: 'Español (Latin America) (es_419)', value: 'es_419', appleLocale: 'es-419' },
  { label: 'Eesti (ET)', value: 'et', appleLocale: 'et' },
  { label: 'Ελληνικά (EL)', value: 'el', appleLocale: 'el' },
  { label: 'فارسی (FA)', value: 'fa', isRTL: true, appleLocale: 'fa' },
  { label: 'لۊری بختیاری (BQI)', value: 'bqi', isRTL: true },
  { label: 'لٛۏری شومالی (LRC)', value: 'lrc', isRTL: true },
  { label: 'Français (FR)', value: 'fr_fr', appleLocale: 'fr' },
  { label: 'Føroyskt (FO)', value: 'fo', appleLocale: 'fo' },
  { label: 'עִברִית (HE)', value: 'he', isRTL: true, appleLocale: 'he' },
  { label: 'Italiano (IT)', value: 'it', appleLocale: 'it' },
  { label: 'Indonesia (ID)', value: 'id_id', appleLocale: 'id' },
  { label: 'Қазақ (KK)', value: 'kk@Cyrl', appleLocale: 'kk' },
  { label: 'Magyar (HU)', value: 'hu_hu', appleLocale: 'hu' },
  { label: '日本語 (JP)', value: 'jp_jp', appleLocale: 'ja' },
  { label: '한국어 (KO)', value: 'ko_kr', appleLocale: 'ko' },
  { label: 'ಕನ್ನಡ (KN)', value: 'kn', appleLocale: 'kn' },
  { label: 'Bahasa Melayu (MS)', value: 'ms', appleLocale: 'ms' },
  { label: 'Nederlands (NL)', value: 'nl_nl', appleLocale: 'nl' },
  { label: 'Nigerian Pidgin (NG)', value: 'pcm' },
  { label: 'नेपाली (NE)', value: 'ne', appleLocale: 'ne' },
  { label: 'Norsk (NB)', value: 'nb_no', appleLocale: 'nb' },
  { label: 'Polski (PL)', value: 'pl', appleLocale: 'pl' },
  { label: 'Português (BR)', value: 'pt_br', appleLocale: 'pt-BR' },
  { label: 'Português (PT)', value: 'pt_pt', appleLocale: 'pt-PT' },
  { label: 'Română (RO)', value: 'ro', appleLocale: 'ro' },
  { label: 'Русский (RU)', value: 'ru', appleLocale: 'ru' },
  { label: 'සිංහල (SI)', value: 'si_lk', appleLocale: 'si' },
  { label: 'Српски (SR)', value: 'sr_rs', appleLocale: 'sr' },
  { label: 'Slovenský (SK)', value: 'sk_sk', appleLocale: 'sk' },
  { label: 'Slovenščina (SL)', value: 'sl_si', appleLocale: 'sl' },
  { label: 'Shqip (SQ)', value: 'sq_AL', appleLocale: 'sq' },
  { label: 'Suomi (FI)', value: 'fi_fi', appleLocale: 'fi' },
  { label: 'Svenska (SE)', value: 'sv_se', appleLocale: 'sv' },
  { label: 'Thai (TH)', value: 'th_th', appleLocale: 'th' },
  { label: 'Vietnamese (VN)', value: 'vi_vn', appleLocale: 'vi' },
  { label: 'Українська (UA)', value: 'ua', appleLocale: 'uk' },
  { label: 'Türkçe (TR)', value: 'tr_tr', appleLocale: 'tr' },
  { label: 'Xhosa (XHO)', value: 'zar_xho', appleLocale: 'xh' },
]);

export type TLanguage = {
  label: string;
  value: string;
  isRTL?: boolean;
  appleLocale?: string;
};
