export const AvailableLanguages = Object.freeze([
  { label: 'English', value: 'en' },
  { label: 'Afrikaans (AFR)', value: 'zar_afr' },
  { label: 'Arabic (AR)', value: 'ar' },
  { label: 'Català (CA)', value: 'ca' },
  { label: 'Chinese (ZH)', value: 'zh_cn' },
  { label: 'Chinese (TW)', value: 'zh_tw' },
  { label: 'Croatian (HR)', value: 'hr_hr' },
  { label: 'Česky (CZ)', value: 'cs_cz' },
  { label: 'Danish (DK)', value: 'da_dk' },
  { label: 'Deutsch (DE)', value: 'de_de' },
  { label: 'Español (Spain) (es_ES)', value: 'es' },
  { label: 'Español (Latin America) (es_419)', value: 'es_419' },
  { label: 'Ελληνικά (EL)', value: 'el' },
  { label: 'Français (FR)', value: 'fr_fr' },
  { label: 'עִברִית', value: 'he' },
  { label: 'Italiano (IT)', value: 'it' },
  { label: 'Indonesia (ID)', value: 'id_id' },
  { label: 'Magyar (HU)', value: 'hu_hu' },
  { label: '日本語 (JP)', value: 'jp_jp' },
  { label: 'Nederlands (NL)', value: 'nl_nl' },
  { label: 'Norsk (NB)', value: 'nb_no' },
  { label: 'Português (BR)', value: 'pt_br' },
  { label: 'Português (PT)', value: 'pt_pt' },
  { label: 'Русский (RU)', value: 'ru' },
  { label: 'Slovenský (SK)', value: 'sk_sk' },
  { label: 'Slovenščina (SL)', value: 'sl_si' },
  { label: 'Suomi (FI)', value: 'fi_fi' },
  { label: 'Svenska (SE)', value: 'sv_se' },
  { label: 'Thai (TH)', value: 'th_th' },
  { label: 'Vietnamese (VN)', value: 'vi_vn' },
  { label: 'Українська (UA)', value: 'ua' },
  { label: 'Türkçe (TR)', value: 'tr_tr' },
  { label: 'Xhosa (XHO)', value: 'zar_xho' },
]);
