export type TLanguage = {
  label: string;
  value: string;
  isRTL?: boolean;
};

// Literal-typed tuple so `LangCode` is a literal union; widened on re-export.
const _availableLanguages = Object.freeze([
  { label: 'English', value: 'en' },
  { label: 'Afrikaans (AFR)', value: 'zar_afr' },
  { label: 'Akan (AK)', value: 'ak' },
  { label: 'Avañeʼẽ (GN)', value: 'gug_PY' },
  { label: 'Azərbaycanca (AZ)', value: 'az' },
  { label: 'Bahasa Melayu (MS)', value: 'ms' },
  { label: 'Català (CA)', value: 'ca' },
  { label: 'Česky (CZ)', value: 'cs_cz' },
  { label: 'Chinese (TW)', value: 'zh_tw' },
  { label: 'Chinese (ZH)', value: 'zh_cn' },
  { label: 'Croatian (HR)', value: 'hr_hr' },
  { label: 'Cymraeg (CY)', value: 'cy' },
  { label: 'Danish (DK)', value: 'da_dk' },
  { label: 'Deutsch (DE)', value: 'de_de' },
  { label: 'Eesti (ET)', value: 'et' },
  { label: 'Español (Latin America) (es_419)', value: 'es_419' },
  { label: 'Español (Spain) (es_ES)', value: 'es' },
  { label: 'Euskara (EU)', value: 'eu' },
  { label: 'Filipino (PH)', value: 'fil_PH' },
  { label: 'Français (FR)', value: 'fr_fr' },
  { label: 'Fulfulde (FF)', value: 'ff' },
  { label: 'Føroyskt (FO)', value: 'fo' },
  { label: 'Indonesia (ID)', value: 'id_id' },
  { label: 'isiZulu (ZU)', value: 'zu_ZA' },
  { label: 'Italiano (IT)', value: 'it' },
  { label: 'Kiswahili (SW)', value: 'sw' },
  { label: 'Latviešu (LV)', value: 'lv' },
  { label: 'Magyar (HU)', value: 'hu_hu' },
  { label: 'Nederlands (NL)', value: 'nl_nl' },
  { label: 'Nigerian Pidgin (NG)', value: 'pcm' },
  { label: 'Norsk (NB)', value: 'nb_no' },
  { label: 'Polski (PL)', value: 'pl' },
  { label: 'Português (BR)', value: 'pt_br' },
  { label: 'Português (PT)', value: 'pt_pt' },
  { label: 'Română (RO)', value: 'ro' },
  { label: 'Sesotho (ST)', value: 'st_ZA' },
  { label: 'Shqip (SQ)', value: 'sq_AL' },
  { label: 'Slovenščina (SL)', value: 'sl_si' },
  { label: 'Slovenský (SK)', value: 'sk_sk' },
  { label: 'Suomi (FI)', value: 'fi_fi' },
  { label: 'Svenska (SE)', value: 'sv_se' },
  { label: 'Thai (TH)', value: 'th_th' },
  { label: 'Türkçe (TR)', value: 'tr_tr' },
  { label: 'Vietnamese (VN)', value: 'vi_vn' },
  { label: 'Xhosa (XHO)', value: 'zar_xho' },
  { label: 'Ελληνικά (EL)', value: 'el' },
  { label: 'Беларускі (BE)', value: 'be' },
  { label: 'Български (BG)', value: 'bg_bg' },
  { label: 'Русский (RU)', value: 'ru' },
  { label: 'Српски (SR)', value: 'sr_rs' },
  { label: 'Українська (UA)', value: 'ua' },
  { label: 'Қазақ (KK)', value: 'kk@Cyrl' },
  { label: 'Հայերեն (HY)', value: 'hy' },
  { label: 'עִברִית (HE)', value: 'he', isRTL: true },
  { label: 'اردو (UR)', value: 'ur', isRTL: true },
  { label: 'العربية (AR)', value: 'ar', isRTL: true },
  { label: 'فارسی (FA)', value: 'fa', isRTL: true },
  { label: 'لٛۏری شومالی (LRC)', value: 'lrc', isRTL: true },
  { label: 'لۊری بختیاری (BQI)', value: 'bqi', isRTL: true },
  { label: 'አማርኛ (AM)', value: 'am' },
  { label: 'नेपाली (NE)', value: 'ne' },
  { label: 'हिन्दी (HI)', value: 'hi' },
  { label: 'বাংলা (BN)', value: 'bn' },
  { label: 'ਪੰਜਾਬੀ (PA)', value: 'pa' },
  { label: 'ಕನ್ನಡ (KN)', value: 'kn' },
  { label: 'සිංහල (SI)', value: 'si_lk' },
  { label: 'ქართული (KA)', value: 'ka' },
  { label: 'ខ្មែរ (KM)', value: 'km' },
  { label: '客家話 (HAK)', value: 'hak' },
  { label: '日本語 (JP)', value: 'jp_jp' },
  { label: '한국어 (KO)', value: 'ko_kr' },
] as const) satisfies readonly TLanguage[];

export const AvailableLanguages: readonly TLanguage[] = _availableLanguages;

// Drives the typed loader Record in loc/index.ts so drift becomes a TS error.
export type LangCode = (typeof _availableLanguages)[number]['value'];
