export const images = {
  Dashboard: require('./images/dashboard.png'),
  DashboardInactive: require('./images/dashboardInactive.png'),
  ContactList: require('./images/addressBook.png'),
  ContactListInactive: require('./images/addressBookInactive.png'),
  Settings: require('./images/settings.png'),
  SettingsInactive: require('./images/settingsInactive.png'),
  success: require('./images/bvWalletIconSuccess.png'),
  dashboardNoWallet: require('./images/bvWalletIconNoCards.png'),
  addressBookNoContacts: require('./images/addressBookNoContacts.png'),
  addressBookNotFound: require('./images/bvAppIconsSearchx2.png'),
  backArrow: require('./images/navigationBarBackArrow.png'),
  nextBlackArrow: require('./images/navigationBarBackArrowCopy.png'),
  successBadge: require('./images/groupCopy2.png'),
  processingState: require('./images/processingState.png'),
  errorState: require('./images/errorState.png'),
  yellowMinus: require('./images/yellowMinus.png'),
  yellowPlus: require('./images/yellowPlus.png'),
  coin: require('./images/coin.png'),
  noTransactions: require('./images/bvWalletIconNoTransactions.png'),
  coinLogoInCircle: require('./images/coinLogoInCircle.png'),
  qrCode: require('./images/qr-code.png'),
  close: require('./images/close.png'),
  closeInverted: require('./images/closeInverted.png'),
  scanQRcrosshair: require('./images/scanQRcrosshair.png'),
  goldWalletLogoBlack: require('./images/bv017LogoGoldWalletRgbV3HorizontalBlack.png'),
  bigMinus: require('./images/bigMinus.png'),
  bigPlus: require('./images/bigPlus.png'),
  cancelSmall: require('./images/cancelSmall.png'),
  portraitLogo: require('./images/portraitLogo.png'),
};

export const icons = {
  iconDropdown: require('./images/iconDropdown.png'),
  search: require('./images/iconSearch.png'),
  addIcon: require('./images/addIcon.png'),
  buildIcon: require('./images/buildIcon.png'),
  dataUsageIcon: require('./images/dataUsageIcon.png'),
  languageIcon: require('./images/languageIcon.png'),
  lockIcon: require('./images/lockIcon.png'),
  infoIcon: require('./images/infoIcon.png'),
  fingerprintIcon: require('./images/fingerprintIcon.png'),
  qrCode: require('./images/qrCode.png'),
  github: require('./images/github.png'),
  star: require('./images/star.png'),
  success: require('./images/success.png'),
  visibilityOn: require('./images/visibilityOn.png'),
  visibilityOff: require('./images/visibilityOff.png'),
  delete: require('./images/icon_delete.png'),
  filter: require('./images/filter.png'),
};
