name: BuildReleaseApkAndPackageAsFlatpak

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  buildReleaseApk:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Specify node version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Use yarn caches
        uses: actions/cache@v2
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use specific Java version for sdkmanager to work
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install node_modules
        run: yarn install

      - name: Extract Version Name
        id: version_name
        run: |
          VERSION_NAME=$(grep versionName android/app/build.gradle | awk '{print $2}' | tr -d '"')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "::set-output name=version_name::$VERSION_NAME"

      - name: Generate Build Number based on timestamp
        run: |
          NEW_BUILD_NUMBER=$(date +%s)
          echo "NEW_BUILD_NUMBER=$NEW_BUILD_NUMBER" >> $GITHUB_ENV
          echo "::set-output name=build_number::$NEW_BUILD_NUMBER"

      - name: Build
        env:
          KEYSTORE_FILE_HEX: ${{ secrets.KEYSTORE_FILE_HEX }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          BUILD_NUMBER: ${{ env.NEW_BUILD_NUMBER }}
        run: ./scripts/build-release-apk.sh

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: BlueWallet-${{ env.VERSION_NAME }}(${{ env.NEW_BUILD_NUMBER }}).apk
          path: ./android/app/build/outputs/apk/release/BlueWallet-${{ env.VERSION_NAME }}(${{ env.NEW_BUILD_NUMBER }}).apk

  buildFlatpak:
    runs-on: ubuntu-latest
    needs: buildReleaseApk

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Download APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: BlueWallet-${{ env.VERSION_NAME }}(${{ env.NEW_BUILD_NUMBER }}).apk

      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Set up Flatpak environment
        run: |
          flatpak install -y flathub org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08

      - name: Create Flatpak Project Directory
        run: |
          mkdir bluewallet-flatpak
          mv BlueWallet-${{ env.VERSION_NAME }}(${{ env.NEW_BUILD_NUMBER }}).apk bluewallet-flatpak/BlueWallet.apk

      - name: Create Flatpak Manifest
        run: |
          cat <<EOF > bluewallet-flatpak/manifest.json
          {
            "app-id": "io.bluewallet.bluewallet",
            "runtime": "org.freedesktop.Platform",
            "runtime-version": "21.08",
            "sdk": "org.freedesktop.Sdk",
            "command": "waydroid",
            "modules": [
              {
                "name": "waydroid",
                "buildsystem": "simple",
                "build-commands": [
                  "install -Dm644 /app/BlueWallet.apk /usr/share/waydroid/BlueWallet.apk"
                ],
                "sources": [
                  {
                    "type": "archive",
                    "url": "https://github.com/waydroid/waydroid/archive/refs/heads/main.zip",
                    "sha256": "sha256-of-the-file"
                  },
                  {
                    "type": "file",
                    "path": "BlueWallet.apk"
                  }
                ]
              }
            ]
          }
          EOF

      - name: Build Flatpak
        run: |
          flatpak-builder --user --install --force-clean build-dir bluewallet-flatpak/manifest.json

      - name: Package Flatpak
        run: |
          flatpak build-export repo build-dir
          flatpak build-bundle repo BlueWallet-${{ env.VERSION_NAME }}(${{ env.NEW_BUILD_NUMBER }}).flatpak io.bluewallet.bluewallet

      - name: Upload Flatpak Artifact
        uses: actions/upload-artifact@v2
        with:
          name: BlueWallet-flatpak
          path: BlueWallet-${{ env.VERSION_NAME }}(${{ env.NEW_BUILD_NUMBER }}).flatpak