name: 'Pull request reviewer reminder'
on:
  schedule:
    # Check reviews every weekday, 10:00 and 17:00
    - cron: '0 10,17 * * 1-5'

jobs:
  pull-request-reviewer-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: tommykw/pull-request-reviewer-reminder-action@v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          reminder_message: 'One business day has passed since the review started. Give priority to reviews as much as possible.' # Required. Messages to send to reviewers on Github.
          review_turnaround_hours: 24 # Required. This is the deadline for reviews. If this time is exceeded, a reminder wil be send.